import { chromium } from '@playwright/test'
const b = await chromium.launch({ executablePath: process.env.EXE })
const p = await b.newPage({ viewport: { width: 1400, height: 900 } })
await p.goto('http://localhost:3999/dark-test', { waitUntil: 'networkidle', timeout: 60000 })
const inp = p.getByPlaceholder('Search pages, competitors…')
await inp.waitFor({ state: 'visible', timeout: 15000 })
// Enter-key navigation to an ungated route
await inp.fill('profile')
await p.waitForTimeout(350)
await inp.press('Enter')
await p.waitForURL('**/profile', { timeout: 8000 }).catch(() => {})
const urlEnter = p.url()
// Click navigation: go back, type, click the result row
await p.goto('http://localhost:3999/dark-test', { waitUntil: 'networkidle' })
const inp2 = p.getByPlaceholder('Search pages, competitors…')
await inp2.waitFor({ state: 'visible' })
await inp2.fill('account')
await p.waitForTimeout(350)
await p.locator('.z-40 button').first().click()
await p.waitForURL('**/profile', { timeout: 8000 }).catch(() => {})
console.log('ENTER_NAV_URL=' + urlEnter)
console.log('CLICK_NAV_URL=' + p.url())
await b.close()
